
PROC MENU
;{

    MOV [NPC_INDEX], 0

GAME_LOOP:

    ;========================
    ; terminou?
    ;========================

    MOV AX, [NPC_INDEX]

    CMP AX, [TOTAL_NPCS]
    JB @@CONTINUE_GAME
    JMP WIN_GAME

    CALL BUTTON_INPUT
    CALL PRINT_BUTTONS

@@CONTINUE_GAME:

    ;========================
    ; limpa tela
    ;========================

    PUSH 0
    PUSH 0
    PUSH 320
    PUSH 200
    PUSH BLACK
    CALL GRAPHICS_PRINTRECT

    ;========================
    ; PASSAPORTE AZUL
    ;========================

    PUSH 15     ; X
    PUSH 10     ; Y
    PUSH 290    ; WIDTH
    PUSH 150    ; HEIGHT
    PUSH 1      ; BLUE
    CALL GRAPHICS_PRINTRECT
    ;=================================================
    ; NPC 1
    ;=================================================

    CMP [NPC_INDEX], 0
    JE @@PRINT_NPC1
    JMP @@NPC2

@@PRINT_NPC1:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1H
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 19
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1I
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 21
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC1J
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 2
    ;=================================================

@@NPC2:

    CMP [NPC_INDEX], 1
    JE @@PRINT_NPC2
    JMP @@NPC3

@@PRINT_NPC2:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC2H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 3
    ;=================================================

@@NPC3:

    CMP [NPC_INDEX], 2
    JE @@PRINT_NPC3
    JMP @@NPC4

@@PRINT_NPC3:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC3H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 4
    ;=================================================

@@NPC4:

    CMP [NPC_INDEX], 3
    JE @@PRINT_NPC4
    JMP @@NPC5

@@PRINT_NPC4:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4H
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 19
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC4I
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 5
    ;=================================================

@@NPC5:

    CMP [NPC_INDEX], 4
    JE @@PRINT_NPC5
    JMP @@NPC6

@@PRINT_NPC5:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC5H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 6
    ;=================================================

@@NPC6:

    CMP [NPC_INDEX], 5
    JE @@PRINT_NPC6
    JMP @@NPC7

@@PRINT_NPC6:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6H
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 19
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6I
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 21
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC6J
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 7
    ;=================================================

@@NPC7:

    CMP [NPC_INDEX], 6
    JE @@PRINT_NPC7
    JMP @@NPC8

@@PRINT_NPC7:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC7H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

        ;=================================================
    ; NPC 8
    ;=================================================

@@NPC8:

    CMP [NPC_INDEX], 7
    JE @@PRINT_NPC8
    JMP @@NPC9

@@PRINT_NPC8:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC8H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 9
    ;=================================================

@@NPC9:

    CMP [NPC_INDEX], 8
    JE @@PRINT_NPC9
    JMP @@NPC10

@@PRINT_NPC9:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC9H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    ;=================================================
    ; NPC 10
    ;=================================================

@@NPC10:

    CMP [NPC_INDEX], 9
    JE @@PRINT_NPC10
    JMP @@AFTER_PRINT

@@PRINT_NPC10:

    PUSH 3
    PUSH 3
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 5
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10B
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 7
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10C
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 9
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10D
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 11
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10E
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 13
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10F
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 15
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10G
    CALL TEXT_COLORSTR

    PUSH 3
    PUSH 17
    CALL TEXT_SET_CURPOS
    PUSH WHITE
    PUSH OFFSET DFNPC10H
    CALL TEXT_COLORSTR

    JMP @@AFTER_PRINT

    @@AFTER_PRINT:

    ;========================
    ; decisão
    ;========================

    PUSH 3
    PUSH 23
    CALL TEXT_SET_CURPOS

    PUSH RED
    PUSH OFFSET TXT_DECISION
    CALL TEXT_COLORSTR

WAIT_INPUT:

    MOV AH, 00h
    INT 16h

    CMP AH, 4Bh
    JNE @@NOT_LEFT
    JMP INPUT_LEFT

@@NOT_LEFT:

    CMP AH, 4Dh
    JNE @@NOT_RIGHT
    JMP INPUT_RIGHT

@@NOT_RIGHT:

    JMP WAIT_INPUT

INPUT_LEFT:

    MOV AL, 1
    JMP CHECK_RESP

INPUT_RIGHT:

    MOV AL, 0

CHECK_RESP:

    MOV BX, [NPC_INDEX]

    MOV SI, OFFSET RESPS
    ADD SI, BX

    MOV BL, [SI]

    CMP AL, BL
    JE @@CORRECT
    JMP GAME_OVER

@@CORRECT:

    PUSH 0
    PUSH 72;Y
    CALL TEXT_SET_CURPOS

    PUSH GREEN
    PUSH OFFSET TXT_OK
    CALL TEXT_COLORSTR

    MOV AH, 00
    INT 16h

    INC [NPC_INDEX]

    JMP GAME_LOOP

GAME_OVER:

    PUSH 0
    PUSH 72;Y
    CALL TEXT_SET_CURPOS

    PUSH RED
    PUSH OFFSET TXT_BAD
    CALL TEXT_COLORSTR

    MOV AH, 00
    INT 16h

    RET

WIN_GAME:

    PUSH 10
    PUSH 12
    CALL TEXT_SET_CURPOS

    PUSH GREEN
    PUSH OFFSET TXT_WIN
    CALL TEXT_COLORSTR

    MOV AH, 00
    INT 16h

    RET

;}
ENDP MENU